# Generated by Django 5.0.6 on 2024-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nota_geral',
            field=models.FloatField(default=0.0),
        ),
    ]
